title: PinBlog
language: zh-CN
author: Len_zh

avatar: /img/Len-zh.jpg

card:
  enable: true
  description: 
    a normal Len_zh!
  iconLinks:
    GitHub: 
      theme: brands
      name: github
      link: https://github.com

background:
  stream: true # 流播开关, 若关闭则只呈现第一个image
  images: 
    - /img/background1.jpg
    - /img/background2.jpg
  interval: 1000 # 图片切换间隔
  transition: 200 # 过渡时长

menu:
  Home:
    name: house
    theme: solid
    link: /
  About:
    name: id-card
    theme: solid
    link: /about/
  Archive:
    name: box-archive
    theme: solid
    link: /archive/


