title: PinBlog
language: zh-CN
author: Len_zh

avatar: /img/Len-zh.jpg

card:
  enable: true
  description: 
    a normal Len_zh!
  iconLinks:
    GitHub: 
      theme: brands
      name: github
      link: https://github.com

menu:
  Home:
    name: house
    theme: solid
    link: /
  About:
    name: id-card
    theme: solid
    link: /about/
  Archive:
    name: box-archive
    theme: solid
    link: /archive/


